#!/usr/bin/env python3
"""Generate the device geometry: three superelliptical (squircle) clip paths in SVG
objectBoundingBox units, plus the percentages that position each layer.

WHY THIS EXISTS. A CSS border-radius is a CIRCULAR arc. Every Apple device uses a
CONTINUOUS corner (a superellipse), and the difference is the single loudest tell that
a phone on a web page was drawn by hand rather than photographed. At the size this site
renders the device the two curves diverge by ~4 CSS px at the diagonal, which a designer
reads instantly as "fake" without being able to name it.

MEASUREMENTS, from Apple's published iPhone 16 Pro dimensions. Nothing here is invented:
  device        71.5 mm x 149.6 mm
  display       1206 x 2622 px at 460 ppi  =  66.6 mm x 144.8 mm
  scale         1206 px / 66.6 mm = 18.11 px per mm
  band+bezel    (71.5 - 66.6) / 2 = 2.45 mm per side = 44.4 px
  of which      ~1.6 mm reads as metal, the rest is black bezel under the glass, which is
                invisible against a dark app and is why a REAL phone's frame reads thin.
  display r     62 pt x 3 = 186 px       (UIScreen corner radius, iPhone 16 Pro)
  device r      186 + 44 = 230 px

The superellipse exponent n = 5 approximates Apple's continuous corner closely enough that
the residual is under a third of a pixel at the sizes we render.
"""
import math

N          = 5.0      # superellipse exponent
SAMPLES    = 26       # points per corner; the residual is invisible well below this
DEV_W, DEV_H = 1295.0, 2709.0     # 71.5mm x 149.6mm at 18.11 px/mm
SCR_W, SCR_H = 1206.0, 2622.0
R_DEVICE   = 230.0
R_SCREEN   = 186.0
METAL      = 30.0     # mm-derived: 1.66 mm of visible titanium
BEZEL      = (DEV_W - SCR_W) / 2 - METAL   # the rest is black bezel


def superellipse_corner(r, n=N, samples=SAMPLES):
    """Quarter of a superellipse of 'radius' r, from (r,0) to (0,r) in corner-local space.
    Point 0 sits on the horizontal edge, point -1 on the vertical edge."""
    pts = []
    for i in range(samples + 1):
        t = (i / samples) * (math.pi / 2)
        x = r * (math.cos(t) ** (2.0 / n))
        y = r * (math.sin(t) ** (2.0 / n))
        pts.append((x, y))
    return pts


def squircle_path(w, h, r, n=N):
    """A closed superelliptical rounded rectangle, in units of the given box, emitted in
    objectBoundingBox space (0..1 on each axis). x is divided by w and y by h, so the path
    is correct for ANY rendered size that preserves this box's aspect ratio."""
    c = superellipse_corner(r, n)
    pts = []
    # top-right corner: from the top edge round to the right edge
    for x, y in reversed(c):
        pts.append((w - r + x, r - y))
    # bottom-right
    for x, y in c:
        pts.append((w - r + x, h - r + y))
    # bottom-left
    for x, y in reversed(c):
        pts.append((r - x, h - r + y))
    # top-left
    for x, y in c:
        pts.append((r - x, r - y))
    d = []
    for i, (x, y) in enumerate(pts):
        d.append(("M" if i == 0 else "L") + f"{x / w:.5f},{y / h:.5f}")
    return "".join(d) + "Z"


def circular_deviation(r, n=N):
    """How far the superellipse sits outside a circular arc of the same radius, at the
    diagonal. This is the number that makes the whole exercise worth doing."""
    t = math.pi / 4
    sx = r * (math.cos(t) ** (2.0 / n))
    sy = r * (math.sin(t) ** (2.0 / n))
    cx = r * math.cos(t)
    cy = r * math.sin(t)
    return math.hypot(sx - cx, sy - cy)


if __name__ == "__main__":
    scr_box_w, scr_box_h = DEV_W - 2 * METAL, DEV_H - 2 * METAL          # black bezel layer
    print("<!-- generated by tools/gen-device.py; do not hand-edit -->")
    print('<svg class="defs" width="0" height="0" aria-hidden="true" focusable="false">')
    print("  <defs>")
    for name, (w, h, r) in {
        "sq-device": (DEV_W, DEV_H, R_DEVICE),
        "sq-bezel":  (scr_box_w, scr_box_h, R_DEVICE - METAL),
        "sq-screen": (SCR_W, SCR_H, R_SCREEN),
    }.items():
        print(f'    <clipPath id="{name}" clipPathUnits="objectBoundingBox">')
        print(f'      <path d="{squircle_path(w, h, r)}"/>')
        print("    </clipPath>")
    print("  </defs>")
    print("</svg>")
    print()
    print("/* geometry, in the units the stylesheet needs */")
    print(f"  device aspect-ratio     {DEV_W:.0f} / {DEV_H:.0f}   = {DEV_W/DEV_H:.5f}")
    print(f"  metal band inset        {100*METAL/DEV_W:.4f}%  of device width  ({METAL:.1f}px)")
    print(f"  black bezel inset       {100*BEZEL/scr_box_w:.4f}%  of bezel-box width ({BEZEL:.1f}px)")
    print(f"  screen aspect-ratio     {SCR_W:.0f} / {SCR_H:.0f}   = {SCR_W/SCR_H:.5f}")
    print(f"  corner gain over circle {circular_deviation(R_DEVICE):.1f}px of {DEV_W:.0f} "
          f"= {100*circular_deviation(R_DEVICE)/DEV_W:.2f}% of device width")
